// An error generated by returning an object .
#include <iostream>
#include <cstring>
#include <cstdlib>
using namespace std;
class samp
{
    char *s;

public:
    samp() { s = NULL; }
    samp(char *str)
    {
        s = (char *)malloc(strlen(str) + 1);
        if (!s)
        {
            cout << " Allocation error \n";
            exit(1);
        }
        strcpy(s, str);
    }
    ~samp()
    {
        if (s)
            free(s);
        cout << " Freeing s\n";
    }

    void show() { cout << s << "\n"; }
    void set(char* str);
};

void samp::set(char* str)
{
    if (s)
        free(s);
    s = (char *)malloc(strlen(str) + 1);
    strcpy(s, str);
}

// Return an object of type samp
samp input()
{
    char s[80];
    samp str;
    cout << " Enter a string : ";
    cin >> s;
    str.set(s);
    return str;
}
int main()
{
    samp ob;
    // assign returned object to ob
    ob = input(); // This causes an error !!!!
    ob.show();
    return 0;
}